services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: mini_blog_postgres
    environment:
      POSTGRES_DB: mini-blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6543:5432"