// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery5
// template: testify

package mocks

import (
	"context"
	"mini-blog/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryI creates a new instance of MockRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryI {
	mock := &MockRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryI is an autogenerated mock type for the RepositoryI type
type MockRepositoryI struct {
	mock.Mock
}

type MockRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryI) EXPECT() *MockRepositoryI_Expecter {
	return &MockRepositoryI_Expecter{mock: &_m.Mock}
}

// CountComments provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CountComments(ctx context.Context, postID int) (int, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CountComments")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CountComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountComments'
type MockRepositoryI_CountComments_Call struct {
	*mock.Call
}

// CountComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) CountComments(ctx interface{}, postID interface{}) *MockRepositoryI_CountComments_Call {
	return &MockRepositoryI_CountComments_Call{Call: _e.mock.On("CountComments", ctx, postID)}
}

func (_c *MockRepositoryI_CountComments_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_CountComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CountComments_Call) Return(n int, err error) *MockRepositoryI_CountComments_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepositoryI_CountComments_Call) RunAndReturn(run func(ctx context.Context, postID int) (int, error)) *MockRepositoryI_CountComments_Call {
	_c.Call.Return(run)
	return _c
}

// CountLikes provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CountLikes(ctx context.Context, postID int) (int, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CountLikes")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CountLikes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLikes'
type MockRepositoryI_CountLikes_Call struct {
	*mock.Call
}

// CountLikes is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) CountLikes(ctx interface{}, postID interface{}) *MockRepositoryI_CountLikes_Call {
	return &MockRepositoryI_CountLikes_Call{Call: _e.mock.On("CountLikes", ctx, postID)}
}

func (_c *MockRepositoryI_CountLikes_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_CountLikes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CountLikes_Call) Return(n int, err error) *MockRepositoryI_CountLikes_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepositoryI_CountLikes_Call) RunAndReturn(run func(ctx context.Context, postID int) (int, error)) *MockRepositoryI_CountLikes_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CreateComment(ctx context.Context, comment entity.Comment) (*entity.Comment, error) {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 *entity.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Comment) (*entity.Comment, error)); ok {
		return returnFunc(ctx, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Comment) *entity.Comment); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Comment) error); ok {
		r1 = returnFunc(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockRepositoryI_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment entity.Comment
func (_e *MockRepositoryI_Expecter) CreateComment(ctx interface{}, comment interface{}) *MockRepositoryI_CreateComment_Call {
	return &MockRepositoryI_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, comment)}
}

func (_c *MockRepositoryI_CreateComment_Call) Run(run func(ctx context.Context, comment entity.Comment)) *MockRepositoryI_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Comment
		if args[1] != nil {
			arg1 = args[1].(entity.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CreateComment_Call) Return(comment1 *entity.Comment, err error) *MockRepositoryI_CreateComment_Call {
	_c.Call.Return(comment1, err)
	return _c
}

func (_c *MockRepositoryI_CreateComment_Call) RunAndReturn(run func(ctx context.Context, comment entity.Comment) (*entity.Comment, error)) *MockRepositoryI_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLike provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CreateLike(ctx context.Context, like entity.Like) (*entity.Like, error) {
	ret := _mock.Called(ctx, like)

	if len(ret) == 0 {
		panic("no return value specified for CreateLike")
	}

	var r0 *entity.Like
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Like) (*entity.Like, error)); ok {
		return returnFunc(ctx, like)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Like) *entity.Like); ok {
		r0 = returnFunc(ctx, like)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Like)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Like) error); ok {
		r1 = returnFunc(ctx, like)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CreateLike_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLike'
type MockRepositoryI_CreateLike_Call struct {
	*mock.Call
}

// CreateLike is a helper method to define mock.On call
//   - ctx context.Context
//   - like entity.Like
func (_e *MockRepositoryI_Expecter) CreateLike(ctx interface{}, like interface{}) *MockRepositoryI_CreateLike_Call {
	return &MockRepositoryI_CreateLike_Call{Call: _e.mock.On("CreateLike", ctx, like)}
}

func (_c *MockRepositoryI_CreateLike_Call) Run(run func(ctx context.Context, like entity.Like)) *MockRepositoryI_CreateLike_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Like
		if args[1] != nil {
			arg1 = args[1].(entity.Like)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CreateLike_Call) Return(like1 *entity.Like, err error) *MockRepositoryI_CreateLike_Call {
	_c.Call.Return(like1, err)
	return _c
}

func (_c *MockRepositoryI_CreateLike_Call) RunAndReturn(run func(ctx context.Context, like entity.Like) (*entity.Like, error)) *MockRepositoryI_CreateLike_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLikeComment provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CreateLikeComment(ctx context.Context, like entity.CommentLike) (*entity.CommentLike, error) {
	ret := _mock.Called(ctx, like)

	if len(ret) == 0 {
		panic("no return value specified for CreateLikeComment")
	}

	var r0 *entity.CommentLike
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.CommentLike) (*entity.CommentLike, error)); ok {
		return returnFunc(ctx, like)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.CommentLike) *entity.CommentLike); ok {
		r0 = returnFunc(ctx, like)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CommentLike)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.CommentLike) error); ok {
		r1 = returnFunc(ctx, like)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CreateLikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLikeComment'
type MockRepositoryI_CreateLikeComment_Call struct {
	*mock.Call
}

// CreateLikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - like entity.CommentLike
func (_e *MockRepositoryI_Expecter) CreateLikeComment(ctx interface{}, like interface{}) *MockRepositoryI_CreateLikeComment_Call {
	return &MockRepositoryI_CreateLikeComment_Call{Call: _e.mock.On("CreateLikeComment", ctx, like)}
}

func (_c *MockRepositoryI_CreateLikeComment_Call) Run(run func(ctx context.Context, like entity.CommentLike)) *MockRepositoryI_CreateLikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.CommentLike
		if args[1] != nil {
			arg1 = args[1].(entity.CommentLike)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CreateLikeComment_Call) Return(commentLike *entity.CommentLike, err error) *MockRepositoryI_CreateLikeComment_Call {
	_c.Call.Return(commentLike, err)
	return _c
}

func (_c *MockRepositoryI_CreateLikeComment_Call) RunAndReturn(run func(ctx context.Context, like entity.CommentLike) (*entity.CommentLike, error)) *MockRepositoryI_CreateLikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CreatePost(ctx context.Context, post entity.Post) (*entity.Post, error) {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *entity.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Post) (*entity.Post, error)); ok {
		return returnFunc(ctx, post)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Post) *entity.Post); ok {
		r0 = returnFunc(ctx, post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Post) error); ok {
		r1 = returnFunc(ctx, post)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockRepositoryI_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - post entity.Post
func (_e *MockRepositoryI_Expecter) CreatePost(ctx interface{}, post interface{}) *MockRepositoryI_CreatePost_Call {
	return &MockRepositoryI_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, post)}
}

func (_c *MockRepositoryI_CreatePost_Call) Run(run func(ctx context.Context, post entity.Post)) *MockRepositoryI_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Post
		if args[1] != nil {
			arg1 = args[1].(entity.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CreatePost_Call) Return(post1 *entity.Post, err error) *MockRepositoryI_CreatePost_Call {
	_c.Call.Return(post1, err)
	return _c
}

func (_c *MockRepositoryI_CreatePost_Call) RunAndReturn(run func(ctx context.Context, post entity.Post) (*entity.Post, error)) *MockRepositoryI_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRepost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CreateRepost(ctx context.Context, repost entity.Repost) (*entity.Repost, error) {
	ret := _mock.Called(ctx, repost)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepost")
	}

	var r0 *entity.Repost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Repost) (*entity.Repost, error)); ok {
		return returnFunc(ctx, repost)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Repost) *entity.Repost); ok {
		r0 = returnFunc(ctx, repost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Repost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Repost) error); ok {
		r1 = returnFunc(ctx, repost)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CreateRepost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepost'
type MockRepositoryI_CreateRepost_Call struct {
	*mock.Call
}

// CreateRepost is a helper method to define mock.On call
//   - ctx context.Context
//   - repost entity.Repost
func (_e *MockRepositoryI_Expecter) CreateRepost(ctx interface{}, repost interface{}) *MockRepositoryI_CreateRepost_Call {
	return &MockRepositoryI_CreateRepost_Call{Call: _e.mock.On("CreateRepost", ctx, repost)}
}

func (_c *MockRepositoryI_CreateRepost_Call) Run(run func(ctx context.Context, repost entity.Repost)) *MockRepositoryI_CreateRepost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Repost
		if args[1] != nil {
			arg1 = args[1].(entity.Repost)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CreateRepost_Call) Return(repost1 *entity.Repost, err error) *MockRepositoryI_CreateRepost_Call {
	_c.Call.Return(repost1, err)
	return _c
}

func (_c *MockRepositoryI_CreateRepost_Call) RunAndReturn(run func(ctx context.Context, repost entity.Repost) (*entity.Repost, error)) *MockRepositoryI_CreateRepost_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) CreateUser(ctx context.Context, user entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepositoryI_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *MockRepositoryI_Expecter) CreateUser(ctx interface{}, user interface{}) *MockRepositoryI_CreateUser_Call {
	return &MockRepositoryI_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockRepositoryI_CreateUser_Call) Run(run func(ctx context.Context, user entity.User)) *MockRepositoryI_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.User
		if args[1] != nil {
			arg1 = args[1].(entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_CreateUser_Call) Return(user1 *entity.User, err error) *MockRepositoryI_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepositoryI_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user entity.User) (*entity.User, error)) *MockRepositoryI_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) DeleteComment(ctx context.Context, comment entity.Comment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Comment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryI_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockRepositoryI_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment entity.Comment
func (_e *MockRepositoryI_Expecter) DeleteComment(ctx interface{}, comment interface{}) *MockRepositoryI_DeleteComment_Call {
	return &MockRepositoryI_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, comment)}
}

func (_c *MockRepositoryI_DeleteComment_Call) Run(run func(ctx context.Context, comment entity.Comment)) *MockRepositoryI_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Comment
		if args[1] != nil {
			arg1 = args[1].(entity.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_DeleteComment_Call) Return(err error) *MockRepositoryI_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryI_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, comment entity.Comment) error) *MockRepositoryI_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLike provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) DeleteLike(ctx context.Context, like entity.Like) error {
	ret := _mock.Called(ctx, like)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLike")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Like) error); ok {
		r0 = returnFunc(ctx, like)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryI_DeleteLike_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLike'
type MockRepositoryI_DeleteLike_Call struct {
	*mock.Call
}

// DeleteLike is a helper method to define mock.On call
//   - ctx context.Context
//   - like entity.Like
func (_e *MockRepositoryI_Expecter) DeleteLike(ctx interface{}, like interface{}) *MockRepositoryI_DeleteLike_Call {
	return &MockRepositoryI_DeleteLike_Call{Call: _e.mock.On("DeleteLike", ctx, like)}
}

func (_c *MockRepositoryI_DeleteLike_Call) Run(run func(ctx context.Context, like entity.Like)) *MockRepositoryI_DeleteLike_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Like
		if args[1] != nil {
			arg1 = args[1].(entity.Like)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_DeleteLike_Call) Return(err error) *MockRepositoryI_DeleteLike_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryI_DeleteLike_Call) RunAndReturn(run func(ctx context.Context, like entity.Like) error) *MockRepositoryI_DeleteLike_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLikeComment provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) DeleteLikeComment(ctx context.Context, likeID int) error {
	ret := _mock.Called(ctx, likeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, likeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryI_DeleteLikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLikeComment'
type MockRepositoryI_DeleteLikeComment_Call struct {
	*mock.Call
}

// DeleteLikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - likeID int
func (_e *MockRepositoryI_Expecter) DeleteLikeComment(ctx interface{}, likeID interface{}) *MockRepositoryI_DeleteLikeComment_Call {
	return &MockRepositoryI_DeleteLikeComment_Call{Call: _e.mock.On("DeleteLikeComment", ctx, likeID)}
}

func (_c *MockRepositoryI_DeleteLikeComment_Call) Run(run func(ctx context.Context, likeID int)) *MockRepositoryI_DeleteLikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_DeleteLikeComment_Call) Return(err error) *MockRepositoryI_DeleteLikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryI_DeleteLikeComment_Call) RunAndReturn(run func(ctx context.Context, likeID int) error) *MockRepositoryI_DeleteLikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) DeletePost(ctx context.Context, post entity.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryI_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockRepositoryI_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - ctx context.Context
//   - post entity.Post
func (_e *MockRepositoryI_Expecter) DeletePost(ctx interface{}, post interface{}) *MockRepositoryI_DeletePost_Call {
	return &MockRepositoryI_DeletePost_Call{Call: _e.mock.On("DeletePost", ctx, post)}
}

func (_c *MockRepositoryI_DeletePost_Call) Run(run func(ctx context.Context, post entity.Post)) *MockRepositoryI_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Post
		if args[1] != nil {
			arg1 = args[1].(entity.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_DeletePost_Call) Return(err error) *MockRepositoryI_DeletePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryI_DeletePost_Call) RunAndReturn(run func(ctx context.Context, post entity.Post) error) *MockRepositoryI_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) DeleteRepost(ctx context.Context, repost entity.Repost) error {
	ret := _mock.Called(ctx, repost)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Repost) error); ok {
		r0 = returnFunc(ctx, repost)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryI_DeleteRepost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepost'
type MockRepositoryI_DeleteRepost_Call struct {
	*mock.Call
}

// DeleteRepost is a helper method to define mock.On call
//   - ctx context.Context
//   - repost entity.Repost
func (_e *MockRepositoryI_Expecter) DeleteRepost(ctx interface{}, repost interface{}) *MockRepositoryI_DeleteRepost_Call {
	return &MockRepositoryI_DeleteRepost_Call{Call: _e.mock.On("DeleteRepost", ctx, repost)}
}

func (_c *MockRepositoryI_DeleteRepost_Call) Run(run func(ctx context.Context, repost entity.Repost)) *MockRepositoryI_DeleteRepost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Repost
		if args[1] != nil {
			arg1 = args[1].(entity.Repost)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_DeleteRepost_Call) Return(err error) *MockRepositoryI_DeleteRepost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryI_DeleteRepost_Call) RunAndReturn(run func(ctx context.Context, repost entity.Repost) error) *MockRepositoryI_DeleteRepost_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentByID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetCommentByID(ctx context.Context, commentID int) (*entity.Comment, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *entity.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*entity.Comment, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *entity.Comment); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetCommentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentByID'
type MockRepositoryI_GetCommentByID_Call struct {
	*mock.Call
}

// GetCommentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int
func (_e *MockRepositoryI_Expecter) GetCommentByID(ctx interface{}, commentID interface{}) *MockRepositoryI_GetCommentByID_Call {
	return &MockRepositoryI_GetCommentByID_Call{Call: _e.mock.On("GetCommentByID", ctx, commentID)}
}

func (_c *MockRepositoryI_GetCommentByID_Call) Run(run func(ctx context.Context, commentID int)) *MockRepositoryI_GetCommentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetCommentByID_Call) Return(comment *entity.Comment, err error) *MockRepositoryI_GetCommentByID_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockRepositoryI_GetCommentByID_Call) RunAndReturn(run func(ctx context.Context, commentID int) (*entity.Comment, error)) *MockRepositoryI_GetCommentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsByCommentLikesDesc provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetCommentsByCommentLikesDesc(ctx context.Context, postID int) ([]*entity.Comment, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByCommentLikesDesc")
	}

	var r0 []*entity.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.Comment, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.Comment); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetCommentsByCommentLikesDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsByCommentLikesDesc'
type MockRepositoryI_GetCommentsByCommentLikesDesc_Call struct {
	*mock.Call
}

// GetCommentsByCommentLikesDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) GetCommentsByCommentLikesDesc(ctx interface{}, postID interface{}) *MockRepositoryI_GetCommentsByCommentLikesDesc_Call {
	return &MockRepositoryI_GetCommentsByCommentLikesDesc_Call{Call: _e.mock.On("GetCommentsByCommentLikesDesc", ctx, postID)}
}

func (_c *MockRepositoryI_GetCommentsByCommentLikesDesc_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_GetCommentsByCommentLikesDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetCommentsByCommentLikesDesc_Call) Return(comments []*entity.Comment, err error) *MockRepositoryI_GetCommentsByCommentLikesDesc_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockRepositoryI_GetCommentsByCommentLikesDesc_Call) RunAndReturn(run func(ctx context.Context, postID int) ([]*entity.Comment, error)) *MockRepositoryI_GetCommentsByCommentLikesDesc_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsByPostID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetCommentsByPostID(ctx context.Context, postID int) ([]*entity.Comment, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByPostID")
	}

	var r0 []*entity.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.Comment, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.Comment); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetCommentsByPostID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsByPostID'
type MockRepositoryI_GetCommentsByPostID_Call struct {
	*mock.Call
}

// GetCommentsByPostID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) GetCommentsByPostID(ctx interface{}, postID interface{}) *MockRepositoryI_GetCommentsByPostID_Call {
	return &MockRepositoryI_GetCommentsByPostID_Call{Call: _e.mock.On("GetCommentsByPostID", ctx, postID)}
}

func (_c *MockRepositoryI_GetCommentsByPostID_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_GetCommentsByPostID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetCommentsByPostID_Call) Return(comments []*entity.Comment, err error) *MockRepositoryI_GetCommentsByPostID_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockRepositoryI_GetCommentsByPostID_Call) RunAndReturn(run func(ctx context.Context, postID int) ([]*entity.Comment, error)) *MockRepositoryI_GetCommentsByPostID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLikeByUserAndComment provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetLikeByUserAndComment(ctx context.Context, userID int, commentID int) (*entity.CommentLike, error) {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetLikeByUserAndComment")
	}

	var r0 *entity.CommentLike
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*entity.CommentLike, error)); ok {
		return returnFunc(ctx, userID, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *entity.CommentLike); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CommentLike)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userID, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetLikeByUserAndComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLikeByUserAndComment'
type MockRepositoryI_GetLikeByUserAndComment_Call struct {
	*mock.Call
}

// GetLikeByUserAndComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - commentID int
func (_e *MockRepositoryI_Expecter) GetLikeByUserAndComment(ctx interface{}, userID interface{}, commentID interface{}) *MockRepositoryI_GetLikeByUserAndComment_Call {
	return &MockRepositoryI_GetLikeByUserAndComment_Call{Call: _e.mock.On("GetLikeByUserAndComment", ctx, userID, commentID)}
}

func (_c *MockRepositoryI_GetLikeByUserAndComment_Call) Run(run func(ctx context.Context, userID int, commentID int)) *MockRepositoryI_GetLikeByUserAndComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetLikeByUserAndComment_Call) Return(commentLike *entity.CommentLike, err error) *MockRepositoryI_GetLikeByUserAndComment_Call {
	_c.Call.Return(commentLike, err)
	return _c
}

func (_c *MockRepositoryI_GetLikeByUserAndComment_Call) RunAndReturn(run func(ctx context.Context, userID int, commentID int) (*entity.CommentLike, error)) *MockRepositoryI_GetLikeByUserAndComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetLikeByUserAndPost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetLikeByUserAndPost(ctx context.Context, userID int, postID int) (*entity.Like, error) {
	ret := _mock.Called(ctx, userID, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetLikeByUserAndPost")
	}

	var r0 *entity.Like
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*entity.Like, error)); ok {
		return returnFunc(ctx, userID, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *entity.Like); ok {
		r0 = returnFunc(ctx, userID, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Like)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userID, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetLikeByUserAndPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLikeByUserAndPost'
type MockRepositoryI_GetLikeByUserAndPost_Call struct {
	*mock.Call
}

// GetLikeByUserAndPost is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - postID int
func (_e *MockRepositoryI_Expecter) GetLikeByUserAndPost(ctx interface{}, userID interface{}, postID interface{}) *MockRepositoryI_GetLikeByUserAndPost_Call {
	return &MockRepositoryI_GetLikeByUserAndPost_Call{Call: _e.mock.On("GetLikeByUserAndPost", ctx, userID, postID)}
}

func (_c *MockRepositoryI_GetLikeByUserAndPost_Call) Run(run func(ctx context.Context, userID int, postID int)) *MockRepositoryI_GetLikeByUserAndPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetLikeByUserAndPost_Call) Return(like *entity.Like, err error) *MockRepositoryI_GetLikeByUserAndPost_Call {
	_c.Call.Return(like, err)
	return _c
}

func (_c *MockRepositoryI_GetLikeByUserAndPost_Call) RunAndReturn(run func(ctx context.Context, userID int, postID int) (*entity.Like, error)) *MockRepositoryI_GetLikeByUserAndPost_Call {
	_c.Call.Return(run)
	return _c
}

// GetLikesByPostID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetLikesByPostID(ctx context.Context, postID int) ([]*entity.Like, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetLikesByPostID")
	}

	var r0 []*entity.Like
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.Like, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.Like); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Like)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetLikesByPostID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLikesByPostID'
type MockRepositoryI_GetLikesByPostID_Call struct {
	*mock.Call
}

// GetLikesByPostID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) GetLikesByPostID(ctx interface{}, postID interface{}) *MockRepositoryI_GetLikesByPostID_Call {
	return &MockRepositoryI_GetLikesByPostID_Call{Call: _e.mock.On("GetLikesByPostID", ctx, postID)}
}

func (_c *MockRepositoryI_GetLikesByPostID_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_GetLikesByPostID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetLikesByPostID_Call) Return(likes []*entity.Like, err error) *MockRepositoryI_GetLikesByPostID_Call {
	_c.Call.Return(likes, err)
	return _c
}

func (_c *MockRepositoryI_GetLikesByPostID_Call) RunAndReturn(run func(ctx context.Context, postID int) ([]*entity.Like, error)) *MockRepositoryI_GetLikesByPostID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostByID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetPostByID(ctx context.Context, postID int) (*entity.Post, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostByID")
	}

	var r0 *entity.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*entity.Post, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *entity.Post); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetPostByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostByID'
type MockRepositoryI_GetPostByID_Call struct {
	*mock.Call
}

// GetPostByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) GetPostByID(ctx interface{}, postID interface{}) *MockRepositoryI_GetPostByID_Call {
	return &MockRepositoryI_GetPostByID_Call{Call: _e.mock.On("GetPostByID", ctx, postID)}
}

func (_c *MockRepositoryI_GetPostByID_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_GetPostByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetPostByID_Call) Return(post *entity.Post, err error) *MockRepositoryI_GetPostByID_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockRepositoryI_GetPostByID_Call) RunAndReturn(run func(ctx context.Context, postID int) (*entity.Post, error)) *MockRepositoryI_GetPostByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosts provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetPosts(ctx context.Context, postID int) ([]*entity.Post, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []*entity.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.Post, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.Post); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockRepositoryI_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *MockRepositoryI_Expecter) GetPosts(ctx interface{}, postID interface{}) *MockRepositoryI_GetPosts_Call {
	return &MockRepositoryI_GetPosts_Call{Call: _e.mock.On("GetPosts", ctx, postID)}
}

func (_c *MockRepositoryI_GetPosts_Call) Run(run func(ctx context.Context, postID int)) *MockRepositoryI_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetPosts_Call) Return(posts []*entity.Post, err error) *MockRepositoryI_GetPosts_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockRepositoryI_GetPosts_Call) RunAndReturn(run func(ctx context.Context, postID int) ([]*entity.Post, error)) *MockRepositoryI_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepostByID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetRepostByID(ctx context.Context, repostID int) (*entity.Repost, error) {
	ret := _mock.Called(ctx, repostID)

	if len(ret) == 0 {
		panic("no return value specified for GetRepostByID")
	}

	var r0 *entity.Repost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*entity.Repost, error)); ok {
		return returnFunc(ctx, repostID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *entity.Repost); ok {
		r0 = returnFunc(ctx, repostID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Repost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, repostID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetRepostByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepostByID'
type MockRepositoryI_GetRepostByID_Call struct {
	*mock.Call
}

// GetRepostByID is a helper method to define mock.On call
//   - ctx context.Context
//   - repostID int
func (_e *MockRepositoryI_Expecter) GetRepostByID(ctx interface{}, repostID interface{}) *MockRepositoryI_GetRepostByID_Call {
	return &MockRepositoryI_GetRepostByID_Call{Call: _e.mock.On("GetRepostByID", ctx, repostID)}
}

func (_c *MockRepositoryI_GetRepostByID_Call) Run(run func(ctx context.Context, repostID int)) *MockRepositoryI_GetRepostByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetRepostByID_Call) Return(repost *entity.Repost, err error) *MockRepositoryI_GetRepostByID_Call {
	_c.Call.Return(repost, err)
	return _c
}

func (_c *MockRepositoryI_GetRepostByID_Call) RunAndReturn(run func(ctx context.Context, repostID int) (*entity.Repost, error)) *MockRepositoryI_GetRepostByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReposts provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetReposts(ctx context.Context) ([]*entity.Repost, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReposts")
	}

	var r0 []*entity.Repost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Repost, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Repost); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Repost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetReposts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReposts'
type MockRepositoryI_GetReposts_Call struct {
	*mock.Call
}

// GetReposts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryI_Expecter) GetReposts(ctx interface{}) *MockRepositoryI_GetReposts_Call {
	return &MockRepositoryI_GetReposts_Call{Call: _e.mock.On("GetReposts", ctx)}
}

func (_c *MockRepositoryI_GetReposts_Call) Run(run func(ctx context.Context)) *MockRepositoryI_GetReposts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetReposts_Call) Return(reposts []*entity.Repost, err error) *MockRepositoryI_GetReposts_Call {
	_c.Call.Return(reposts, err)
	return _c
}

func (_c *MockRepositoryI_GetReposts_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Repost, error)) *MockRepositoryI_GetReposts_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepostsByUserID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetRepostsByUserID(ctx context.Context, userID int) ([]*entity.Repost, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRepostsByUserID")
	}

	var r0 []*entity.Repost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.Repost, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.Repost); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Repost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetRepostsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepostsByUserID'
type MockRepositoryI_GetRepostsByUserID_Call struct {
	*mock.Call
}

// GetRepostsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepositoryI_Expecter) GetRepostsByUserID(ctx interface{}, userID interface{}) *MockRepositoryI_GetRepostsByUserID_Call {
	return &MockRepositoryI_GetRepostsByUserID_Call{Call: _e.mock.On("GetRepostsByUserID", ctx, userID)}
}

func (_c *MockRepositoryI_GetRepostsByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockRepositoryI_GetRepostsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetRepostsByUserID_Call) Return(reposts []*entity.Repost, err error) *MockRepositoryI_GetRepostsByUserID_Call {
	_c.Call.Return(reposts, err)
	return _c
}

func (_c *MockRepositoryI_GetRepostsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*entity.Repost, error)) *MockRepositoryI_GetRepostsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepositoryI_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepositoryI_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockRepositoryI_GetUserByEmail_Call {
	return &MockRepositoryI_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockRepositoryI_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepositoryI_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetUserByEmail_Call) Return(user *entity.User, err error) *MockRepositoryI_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepositoryI_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entity.User, error)) *MockRepositoryI_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) GetUserByID(ctx context.Context, userID int) (*entity.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*entity.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *entity.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepositoryI_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepositoryI_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockRepositoryI_GetUserByID_Call {
	return &MockRepositoryI_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockRepositoryI_GetUserByID_Call) Run(run func(ctx context.Context, userID int)) *MockRepositoryI_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_GetUserByID_Call) Return(user *entity.User, err error) *MockRepositoryI_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepositoryI_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int) (*entity.User, error)) *MockRepositoryI_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPosts provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) SearchPosts(ctx context.Context, userID int, query string, offset int, limit int) ([]*entity.Post, int64, error) {
	ret := _mock.Called(ctx, userID, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchPosts")
	}

	var r0 []*entity.Post
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, int, int) ([]*entity.Post, int64, error)); ok {
		return returnFunc(ctx, userID, query, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, int, int) []*entity.Post); ok {
		r0 = returnFunc(ctx, userID, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, int, int) int64); ok {
		r1 = returnFunc(ctx, userID, query, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, string, int, int) error); ok {
		r2 = returnFunc(ctx, userID, query, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoryI_SearchPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPosts'
type MockRepositoryI_SearchPosts_Call struct {
	*mock.Call
}

// SearchPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - query string
//   - offset int
//   - limit int
func (_e *MockRepositoryI_Expecter) SearchPosts(ctx interface{}, userID interface{}, query interface{}, offset interface{}, limit interface{}) *MockRepositoryI_SearchPosts_Call {
	return &MockRepositoryI_SearchPosts_Call{Call: _e.mock.On("SearchPosts", ctx, userID, query, offset, limit)}
}

func (_c *MockRepositoryI_SearchPosts_Call) Run(run func(ctx context.Context, userID int, query string, offset int, limit int)) *MockRepositoryI_SearchPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepositoryI_SearchPosts_Call) Return(posts []*entity.Post, n int64, err error) *MockRepositoryI_SearchPosts_Call {
	_c.Call.Return(posts, n, err)
	return _c
}

func (_c *MockRepositoryI_SearchPosts_Call) RunAndReturn(run func(ctx context.Context, userID int, query string, offset int, limit int) ([]*entity.Post, int64, error)) *MockRepositoryI_SearchPosts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) UpdateComment(ctx context.Context, comment entity.Comment) (*entity.Comment, error) {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 *entity.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Comment) (*entity.Comment, error)); ok {
		return returnFunc(ctx, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Comment) *entity.Comment); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Comment) error); ok {
		r1 = returnFunc(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockRepositoryI_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment entity.Comment
func (_e *MockRepositoryI_Expecter) UpdateComment(ctx interface{}, comment interface{}) *MockRepositoryI_UpdateComment_Call {
	return &MockRepositoryI_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, comment)}
}

func (_c *MockRepositoryI_UpdateComment_Call) Run(run func(ctx context.Context, comment entity.Comment)) *MockRepositoryI_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Comment
		if args[1] != nil {
			arg1 = args[1].(entity.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_UpdateComment_Call) Return(comment1 *entity.Comment, err error) *MockRepositoryI_UpdateComment_Call {
	_c.Call.Return(comment1, err)
	return _c
}

func (_c *MockRepositoryI_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, comment entity.Comment) (*entity.Comment, error)) *MockRepositoryI_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) UpdatePost(ctx context.Context, post entity.Post) (*entity.Post, error) {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 *entity.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Post) (*entity.Post, error)); ok {
		return returnFunc(ctx, post)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Post) *entity.Post); ok {
		r0 = returnFunc(ctx, post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Post) error); ok {
		r1 = returnFunc(ctx, post)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_UpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePost'
type MockRepositoryI_UpdatePost_Call struct {
	*mock.Call
}

// UpdatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - post entity.Post
func (_e *MockRepositoryI_Expecter) UpdatePost(ctx interface{}, post interface{}) *MockRepositoryI_UpdatePost_Call {
	return &MockRepositoryI_UpdatePost_Call{Call: _e.mock.On("UpdatePost", ctx, post)}
}

func (_c *MockRepositoryI_UpdatePost_Call) Run(run func(ctx context.Context, post entity.Post)) *MockRepositoryI_UpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Post
		if args[1] != nil {
			arg1 = args[1].(entity.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_UpdatePost_Call) Return(post1 *entity.Post, err error) *MockRepositoryI_UpdatePost_Call {
	_c.Call.Return(post1, err)
	return _c
}

func (_c *MockRepositoryI_UpdatePost_Call) RunAndReturn(run func(ctx context.Context, post entity.Post) (*entity.Post, error)) *MockRepositoryI_UpdatePost_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepost provides a mock function for the type MockRepositoryI
func (_mock *MockRepositoryI) UpdateRepost(ctx context.Context, repost entity.Repost) (*entity.Repost, error) {
	ret := _mock.Called(ctx, repost)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepost")
	}

	var r0 *entity.Repost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Repost) (*entity.Repost, error)); ok {
		return returnFunc(ctx, repost)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Repost) *entity.Repost); ok {
		r0 = returnFunc(ctx, repost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Repost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Repost) error); ok {
		r1 = returnFunc(ctx, repost)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryI_UpdateRepost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepost'
type MockRepositoryI_UpdateRepost_Call struct {
	*mock.Call
}

// UpdateRepost is a helper method to define mock.On call
//   - ctx context.Context
//   - repost entity.Repost
func (_e *MockRepositoryI_Expecter) UpdateRepost(ctx interface{}, repost interface{}) *MockRepositoryI_UpdateRepost_Call {
	return &MockRepositoryI_UpdateRepost_Call{Call: _e.mock.On("UpdateRepost", ctx, repost)}
}

func (_c *MockRepositoryI_UpdateRepost_Call) Run(run func(ctx context.Context, repost entity.Repost)) *MockRepositoryI_UpdateRepost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Repost
		if args[1] != nil {
			arg1 = args[1].(entity.Repost)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryI_UpdateRepost_Call) Return(repost1 *entity.Repost, err error) *MockRepositoryI_UpdateRepost_Call {
	_c.Call.Return(repost1, err)
	return _c
}

func (_c *MockRepositoryI_UpdateRepost_Call) RunAndReturn(run func(ctx context.Context, repost entity.Repost) (*entity.Repost, error)) *MockRepositoryI_UpdateRepost_Call {
	_c.Call.Return(run)
	return _c
}
